### ISSUE TITLE
Support for SAML enabled Ops Manager

### ISSUE THREAD

**Issue by haydonryan** [rahul-kj/concourse-vsphere#14]
Hey Rahul,
 We've just enabled SAML auth in Ops Manager, which means that we can't use username and password to connect using OM.  

Would it be possible to have options for your pipelines (which are awesome by the way) to include support for calling:
```
Usage: om [options] <command> [<args>]
  --client-id, -c, OM_CLIENT_ID          string  Client ID for the Ops Manager VM (not required for unauthenticated commands)
  --client-secret, -s, OM_CLIENT_SECRET  string  Client Secret for the Ops Manager VM (not required for unauthenticated commands)
```
as well as username and password.

(apologies for the issue, I wanted to reach out, but slack is down)
H

**Comment by rahulkj** [comment]
Closing this as a new version is soon going to be published @haydonryan
